server:
  port: 8000

spring:
  profiles:
    active: develop

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: ${DB_ENGINE}://${DB_HOST}/usermanagement
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 50
      minimum-idle: 35
    driver-class-name: d
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-master.xml
  jackson:
    serialization.write_dates_as_timestamps: false
    date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat
  jpa:
    generate-ddl: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate.jdbc.lob.non_contextual_creation: true
    show-sql: true
